name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  terraform-init:
    needs: test
    uses: ./.github/workflows/terraform-init.yml

  terraform-plan:
    needs: terraform-init
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit

  docker:
    needs: terraform-plan
    uses: ./.github/workflows/docker.yml
